name: Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: Import GPG key
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
      - name: Gradle build
        run: |
          ./gradlew clean build -i
      - name: Run a one-line script
        run: echo ls build/libs


#  build-upstream:
#    name: ${{ github.event.client_payload.message }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#      - name: Build
#        run: |
#          unset GEM_PATH GEM_HOME JRUBY_OPTS
#          ./ci/test-asciidoctor-upstream.sh ${{ github.event.client_payload.branch }}
