name: Release

on:
  workflow_dispatch:
    inputs: {}


jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: Gradle build
        run: |
          ./gradlew clean build -PsigningKey=${{secrets.GPG_PRIVATE_KEY}} -Psigning.password=${{secrets.PASSPHRASE}}
      - name: Run a one-line script
        run: ls build/libs


#  build-upstream:
#    name: ${{ github.event.client_payload.message }}
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '11'
#      - name: Build
#        run: |
#          unset GEM_PATH GEM_HOME JRUBY_OPTS
#          ./ci/test-asciidoctor-upstream.sh ${{ github.event.client_payload.branch }}
