name: Release Sth
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Octo Organization
      - name: Set env vars
        env:
          A: B
          #ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_KEY_ID }}
          #ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          #ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}
      - name: Gradle build
        run: |
          ./gradlew clean build -i
      - name: Run a one-line script
        run: echo ls build/libs
